export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const SUBMIT_FAIL = "SUBMIT_FAIL";
export const FETCH_DATA_ON_BEGIN = "FETCH_DATA_ON_BEGIN";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
